using Normal.Realtime.Serialization;
using UnityEngine;

[RealtimeModel]
public partial class GameStateModel
{
    [RealtimeProperty(1, true, true)]
    public GameStates.States _state;

}


/* ----- Begin Normal Autogenerated Code ----- */
public partial class GameStateModel : IModel {
    // Properties
    public GameStates.States state {
        get { return _cache.LookForValueInCache(_state, entry => entry.stateSet, entry => entry.state); }
        set { if (value == state) return; _cache.UpdateLocalCache(entry => { entry.stateSet = true; entry.state = value; return entry; }); FireStateDidChange(value); }
    }
    
    // Events
    public delegate void StateDidChange(GameStateModel model, GameStates.States value);
    public event         StateDidChange stateDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool              stateSet;
        public GameStates.States state;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public GameStateModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireStateDidChange(GameStates.States value) {
        try {
            if (stateDidChange != null)
                stateDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        State = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _state = state;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteVarint32Length((uint)PropertyID.State, (uint)_state);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.stateSet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.State, (uint)entry.state);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteVarint32((uint)PropertyID.State, (uint)_state);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.stateSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.stateSet)
                    stream.WriteVarint32((uint)PropertyID.State, (uint)entry.state);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool stateExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.stateSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.State: {
                    GameStates.States previousValue = _state;
                    
                    _state = (GameStates.States)stream.ReadVarint32();
                    
                    if (!stateExistsInChangeCache && _state != previousValue)
                        FireStateDidChange(_state);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
