using System.Collections;
using System.Collections.Generic;
using UnityEngine;

using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class SpawnSlotsModel
{
    [RealtimeProperty(1,true,false)]
    public int _slotsUsed;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class SpawnSlotsModel : IModel {
    // Properties
    public int slotsUsed {
        get { return _cache.LookForValueInCache(_slotsUsed, entry => entry.slotsUsedSet, entry => entry.slotsUsed); }
        set { if (value == slotsUsed) return; _cache.UpdateLocalCache(entry => { entry.slotsUsedSet = true; entry.slotsUsed = value; return entry; }); }
    }
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool slotsUsedSet;
        public int  slotsUsed;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public SpawnSlotsModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Serialization
    enum PropertyID {
        SlotsUsed = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _slotsUsed = slotsUsed;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteVarint32Length((uint)PropertyID.SlotsUsed, (uint)_slotsUsed);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.slotsUsedSet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.SlotsUsed, (uint)entry.slotsUsed);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteVarint32((uint)PropertyID.SlotsUsed, (uint)_slotsUsed);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.slotsUsedSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.slotsUsedSet)
                    stream.WriteVarint32((uint)PropertyID.SlotsUsed, (uint)entry.slotsUsed);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.SlotsUsed: {
                    _slotsUsed = (int)stream.ReadVarint32();
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
